# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Secret management for auth
    environment: nisar-auth

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Sets up R
      - name: R setup
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true # Use compiled R binaries for Linux
        
      - name: Install nisar package
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_github("landscape-modeling-lab/nisar")'
      
      - name: NISAR S3 auth
        env:
          EDL_TOKEN: ${{ secrets.EDL_TOKEN }}
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
        run: |
          Rscript -e 'nisar::s3_auth(verbose = TRUE)'